dist: release
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  main: .
  binary: kaffeine
  goos:
    - linux
    - darwin
  goarch:
    - amd64
    - arm64
archives:
- id: tarball
  format: tar.gz
- id: bin
  format: binary
  wrap_in_directory: false
  name_template: "kaffeine_{{ .Os }}_{{ .Arch }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'